//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "Company.Assignment_test.Assignment_testDiagram")]

namespace Company.Assignment_test
{
	/// <summary>
	/// DomainClass Assignment_testDiagram
	/// Description for Company.Assignment_test.Assignment_testDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("Company.Assignment_test.Assignment_testDiagram.DisplayName", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Company.Assignment_test.Assignment_testDiagram.Description", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Company.Assignment_test.Assignment_testDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("795f0ef9-182a-4c94-b7dc-183ed113c89f")]
	public partial class Assignment_testDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::Company.Assignment_test.Assignment_testToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		
		/// <summary>
		/// Most connectors are mapped to element links, but there can be exceptions. This method tell if a connector should be
		/// mapped to an element link.
		/// </summary>
		public override bool IsConnectorMappedToLink(DslDiagrams::BinaryLinkShape connector)
		{
			#region Check Parameters
			global::System.Diagnostics.Debug.Assert(connector != null);
			if (connector == null)
				throw new global::System.ArgumentNullException("connector");
			#endregion
			if (connector.GetType() == typeof(global::Company.Assignment_test.ExampleConnector))
				return false;
			return base.IsConnectorMappedToLink(connector);
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::Company.Assignment_test.Systematic_impact_level)
			{
				global::Company.Assignment_test.Systematic_shape newShape = new global::Company.Assignment_test.Systematic_shape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.Assignment_test.Enabling_impact_level)
			{
				global::Company.Assignment_test.Enabling_shape newShape = new global::Company.Assignment_test.Enabling_shape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.Assignment_test.Immediate_impact_level)
			{
				global::Company.Assignment_test.Immediate_shape newShape = new global::Company.Assignment_test.Immediate_shape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.Assignment_test.Solution_name)
			{
				global::Company.Assignment_test.Solution_name_shape newShape = new global::Company.Assignment_test.Solution_name_shape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::Company.Assignment_test.Concern)
			{
				global::Company.Assignment_test.Concern_shape newShape = new global::Company.Assignment_test.Concern_shape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::Company.Assignment_test.Systematic_shape.DecoratorsInitialized += Systematic_shapeDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for Systematic_shape.
		/// </summary>
		internal static partial class Systematic_shapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for Systematic_shape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::Company.Assignment_test.Systematic_impact_level.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::Company.Assignment_test.ExampleRelationshipConnectAction exampleRelationshipConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::Company.Assignment_test.Assignment_testToolboxHelper.ExampleRelationshipFilterString))
				{
					if (this.exampleRelationshipConnectAction == null)
					{
						this.exampleRelationshipConnectAction = new global::Company.Assignment_test.ExampleRelationshipConnectAction(this);
						this.exampleRelationshipConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.exampleRelationshipConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.exampleRelationshipConnectAction != null)
					{
						this.exampleRelationshipConnectAction.Dispose();
						this.exampleRelationshipConnectAction = null;
					}
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// Assignment_testDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x795f0ef9, 0x182a, 0x4c94, 0xb7, 0xdc, 0x18, 0x3e, 0xd1, 0x13, 0xc8, 0x9f);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Assignment_testDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Assignment_testDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace Company.Assignment_test
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::Company.Assignment_test.Systematic_impact_level), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.Assignment_test.Enabling_impact_level), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.Assignment_test.Immediate_impact_level), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.Assignment_test.Solution_name), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::Company.Assignment_test.Concern), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is global::Company.Assignment_test.Systematic_impact_level)
				{
					parentElement = GetParentForSystematic_impact_level((global::Company.Assignment_test.Systematic_impact_level)childElement);
				} else
				if(childElement is global::Company.Assignment_test.Enabling_impact_level)
				{
					parentElement = GetParentForEnabling_impact_level((global::Company.Assignment_test.Enabling_impact_level)childElement);
				} else
				if(childElement is global::Company.Assignment_test.Immediate_impact_level)
				{
					parentElement = GetParentForImmediate_impact_level((global::Company.Assignment_test.Immediate_impact_level)childElement);
				} else
				if(childElement is global::Company.Assignment_test.Solution_name)
				{
					parentElement = GetParentForSolution_name((global::Company.Assignment_test.Solution_name)childElement);
				} else
				if(childElement is global::Company.Assignment_test.Concern)
				{
					parentElement = GetParentForConcern((global::Company.Assignment_test.Concern)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::Company.Assignment_test.SoSA GetParentForSystematic_impact_level( global::Company.Assignment_test.Systematic_impact_level root )
			{
				// Segments 0 and 1
				global::Company.Assignment_test.SoSA result = root.SoSA;
				if ( result == null ) return null;
				return result;
			}
			public static global::Company.Assignment_test.SoSA GetParentForEnabling_impact_level( global::Company.Assignment_test.Enabling_impact_level root )
			{
				// Segments 0 and 1
				global::Company.Assignment_test.Systematic_impact_level root2 = root.Systematic_impact_level;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Company.Assignment_test.SoSA result = root2.SoSA;
				if ( result == null ) return null;
				return result;
			}
			public static global::Company.Assignment_test.SoSA GetParentForImmediate_impact_level( global::Company.Assignment_test.Immediate_impact_level root )
			{
				// Segments 0 and 1
				global::Company.Assignment_test.Enabling_impact_level root2 = root.Enabling_impact_level;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Company.Assignment_test.Systematic_impact_level root4 = root2.Systematic_impact_level;
				if ( root4 == null ) return null;
				// Segments 4 and 5
				global::Company.Assignment_test.SoSA result = root4.SoSA;
				if ( result == null ) return null;
				return result;
			}
			public static global::Company.Assignment_test.SoSA GetParentForSolution_name( global::Company.Assignment_test.Solution_name root )
			{
				// Segments 0 and 1
				global::Company.Assignment_test.Immediate_impact_level root2 = root.Immediate_impact_level;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::Company.Assignment_test.Enabling_impact_level root4 = root2.Enabling_impact_level;
				if ( root4 == null ) return null;
				// Segments 4 and 5
				global::Company.Assignment_test.Systematic_impact_level root6 = root4.Systematic_impact_level;
				if ( root6 == null ) return null;
				// Segments 6 and 7
				global::Company.Assignment_test.SoSA result = root6.SoSA;
				if ( result == null ) return null;
				return result;
			}
			public static global::Company.Assignment_test.SoSA GetParentForConcern( global::Company.Assignment_test.Concern root )
			{
				// Segments 0 and 1
				global::Company.Assignment_test.SoSA result = root.SoSA;
				if ( result == null ) return null;
				return result;
			}
		}
		
	
	}
