//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace Company.Assignment_test
{
	/// <summary>
	/// DomainModel Assignment_testDomainModel
	/// Description for Company.Assignment_test.Assignment_test
	/// </summary>
	[DslDesign::DisplayNameResource("Company.Assignment_test.Assignment_testDomainModel.DisplayName", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Company.Assignment_test.Assignment_testDomainModel.Description", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("26551814-34ca-49ed-abb2-567b0af36c76")]
	public partial class Assignment_testDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// Assignment_testDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x26551814, 0x34ca, 0x49ed, 0xab, 0xb2, 0x56, 0x7b, 0x0a, 0xf3, 0x6c, 0x76);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public Assignment_testDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(SoSA),
				typeof(Systematic_impact_level),
				typeof(Enabling_impact_level),
				typeof(Immediate_impact_level),
				typeof(Solution_name),
				typeof(Concern),
				typeof(SocialConcern),
				typeof(TechnicalConcern),
				typeof(EnvironmentalConcern),
				typeof(EconomicConcern),
				typeof(SoSAHasElements),
				typeof(Systematic_impact_levelReferencesTargets),
				typeof(Systematic_impact_levelHasEnabling_impact_level),
				typeof(Enabling_impact_levelHasImmediate_impact_level),
				typeof(Immediate_impact_levelHasSolution_name),
				typeof(ConcernReferencesTargetConcern),
				typeof(Systematic_impact_levelHasConcern),
				typeof(Enabling_impact_levelHasConcern),
				typeof(Immediate_impact_levelHasConcern),
				typeof(Assignment_testDiagram),
				typeof(ExampleConnector),
				typeof(Systematic_shape),
				typeof(Enabling_shape),
				typeof(Immediate_shape),
				typeof(Solution_name_shape),
				typeof(ConcernShape),
				typeof(SocialConcernShape),
				typeof(TechnicalConcernShape),
				typeof(EnvironmentalConcernShape),
				typeof(EconomicConcernShape),
				typeof(global::Company.Assignment_test.FixUpDiagram),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Systematic_impact_level), "Name", Systematic_impact_level.NameDomainPropertyId, typeof(Systematic_impact_level.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Concern), "Name", Concern.NameDomainPropertyId, typeof(Concern.NamePropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(SoSAHasElements), "SoSA", SoSAHasElements.SoSADomainRoleId),
				new DomainRolePlayerInfo(typeof(SoSAHasElements), "Element", SoSAHasElements.ElementDomainRoleId),
				new DomainRolePlayerInfo(typeof(Systematic_impact_levelReferencesTargets), "Source", Systematic_impact_levelReferencesTargets.SourceDomainRoleId),
				new DomainRolePlayerInfo(typeof(Systematic_impact_levelReferencesTargets), "Target", Systematic_impact_levelReferencesTargets.TargetDomainRoleId),
				new DomainRolePlayerInfo(typeof(Systematic_impact_levelHasEnabling_impact_level), "Systematic_impact_level", Systematic_impact_levelHasEnabling_impact_level.Systematic_impact_levelDomainRoleId),
				new DomainRolePlayerInfo(typeof(Systematic_impact_levelHasEnabling_impact_level), "Enabling_impact_level", Systematic_impact_levelHasEnabling_impact_level.Enabling_impact_levelDomainRoleId),
				new DomainRolePlayerInfo(typeof(Enabling_impact_levelHasImmediate_impact_level), "Enabling_impact_level", Enabling_impact_levelHasImmediate_impact_level.Enabling_impact_levelDomainRoleId),
				new DomainRolePlayerInfo(typeof(Enabling_impact_levelHasImmediate_impact_level), "Immediate_impact_level", Enabling_impact_levelHasImmediate_impact_level.Immediate_impact_levelDomainRoleId),
				new DomainRolePlayerInfo(typeof(Immediate_impact_levelHasSolution_name), "Immediate_impact_level", Immediate_impact_levelHasSolution_name.Immediate_impact_levelDomainRoleId),
				new DomainRolePlayerInfo(typeof(Immediate_impact_levelHasSolution_name), "Solution_name", Immediate_impact_levelHasSolution_name.Solution_nameDomainRoleId),
				new DomainRolePlayerInfo(typeof(ConcernReferencesTargetConcern), "SourceConcern", ConcernReferencesTargetConcern.SourceConcernDomainRoleId),
				new DomainRolePlayerInfo(typeof(ConcernReferencesTargetConcern), "TargetConcern", ConcernReferencesTargetConcern.TargetConcernDomainRoleId),
				new DomainRolePlayerInfo(typeof(Systematic_impact_levelHasConcern), "Systematic_impact_level", Systematic_impact_levelHasConcern.Systematic_impact_levelDomainRoleId),
				new DomainRolePlayerInfo(typeof(Systematic_impact_levelHasConcern), "Concern", Systematic_impact_levelHasConcern.ConcernDomainRoleId),
				new DomainRolePlayerInfo(typeof(Enabling_impact_levelHasConcern), "Enabling_impact_level", Enabling_impact_levelHasConcern.Enabling_impact_levelDomainRoleId),
				new DomainRolePlayerInfo(typeof(Enabling_impact_levelHasConcern), "Concern", Enabling_impact_levelHasConcern.ConcernDomainRoleId),
				new DomainRolePlayerInfo(typeof(Immediate_impact_levelHasConcern), "Immediate_impact_level", Immediate_impact_levelHasConcern.Immediate_impact_levelDomainRoleId),
				new DomainRolePlayerInfo(typeof(Immediate_impact_levelHasConcern), "Concern", Immediate_impact_levelHasConcern.ConcernDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(21);
				createElementMap.Add(typeof(SoSA), 0);
				createElementMap.Add(typeof(Systematic_impact_level), 1);
				createElementMap.Add(typeof(Enabling_impact_level), 2);
				createElementMap.Add(typeof(Immediate_impact_level), 3);
				createElementMap.Add(typeof(Solution_name), 4);
				createElementMap.Add(typeof(Concern), 5);
				createElementMap.Add(typeof(SocialConcern), 6);
				createElementMap.Add(typeof(TechnicalConcern), 7);
				createElementMap.Add(typeof(EnvironmentalConcern), 8);
				createElementMap.Add(typeof(EconomicConcern), 9);
				createElementMap.Add(typeof(Assignment_testDiagram), 10);
				createElementMap.Add(typeof(ExampleConnector), 11);
				createElementMap.Add(typeof(Systematic_shape), 12);
				createElementMap.Add(typeof(Enabling_shape), 13);
				createElementMap.Add(typeof(Immediate_shape), 14);
				createElementMap.Add(typeof(Solution_name_shape), 15);
				createElementMap.Add(typeof(ConcernShape), 16);
				createElementMap.Add(typeof(SocialConcernShape), 17);
				createElementMap.Add(typeof(TechnicalConcernShape), 18);
				createElementMap.Add(typeof(EnvironmentalConcernShape), 19);
				createElementMap.Add(typeof(EconomicConcernShape), 20);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::Company.Assignment_test.Assignment_testDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new SoSA(partition, propertyAssignments);
				case 1: return new Systematic_impact_level(partition, propertyAssignments);
				case 2: return new Enabling_impact_level(partition, propertyAssignments);
				case 3: return new Immediate_impact_level(partition, propertyAssignments);
				case 4: return new Solution_name(partition, propertyAssignments);
				case 5: return new Concern(partition, propertyAssignments);
				case 6: return new SocialConcern(partition, propertyAssignments);
				case 7: return new TechnicalConcern(partition, propertyAssignments);
				case 8: return new EnvironmentalConcern(partition, propertyAssignments);
				case 9: return new EconomicConcern(partition, propertyAssignments);
				case 10: return new Assignment_testDiagram(partition, propertyAssignments);
				case 11: return new ExampleConnector(partition, propertyAssignments);
				case 12: return new Systematic_shape(partition, propertyAssignments);
				case 13: return new Enabling_shape(partition, propertyAssignments);
				case 14: return new Immediate_shape(partition, propertyAssignments);
				case 15: return new Solution_name_shape(partition, propertyAssignments);
				case 16: return new ConcernShape(partition, propertyAssignments);
				case 17: return new SocialConcernShape(partition, propertyAssignments);
				case 18: return new TechnicalConcernShape(partition, propertyAssignments);
				case 19: return new EnvironmentalConcernShape(partition, propertyAssignments);
				case 20: return new EconomicConcernShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(9);
				createElementLinkMap.Add(typeof(SoSAHasElements), 0);
				createElementLinkMap.Add(typeof(Systematic_impact_levelReferencesTargets), 1);
				createElementLinkMap.Add(typeof(Systematic_impact_levelHasEnabling_impact_level), 2);
				createElementLinkMap.Add(typeof(Enabling_impact_levelHasImmediate_impact_level), 3);
				createElementLinkMap.Add(typeof(Immediate_impact_levelHasSolution_name), 4);
				createElementLinkMap.Add(typeof(ConcernReferencesTargetConcern), 5);
				createElementLinkMap.Add(typeof(Systematic_impact_levelHasConcern), 6);
				createElementLinkMap.Add(typeof(Enabling_impact_levelHasConcern), 7);
				createElementLinkMap.Add(typeof(Immediate_impact_levelHasConcern), 8);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::Company.Assignment_test.Assignment_testDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new SoSAHasElements(partition, roleAssignments, propertyAssignments);
				case 1: return new Systematic_impact_levelReferencesTargets(partition, roleAssignments, propertyAssignments);
				case 2: return new Systematic_impact_levelHasEnabling_impact_level(partition, roleAssignments, propertyAssignments);
				case 3: return new Enabling_impact_levelHasImmediate_impact_level(partition, roleAssignments, propertyAssignments);
				case 4: return new Immediate_impact_levelHasSolution_name(partition, roleAssignments, propertyAssignments);
				case 5: return new ConcernReferencesTargetConcern(partition, roleAssignments, propertyAssignments);
				case 6: return new Systematic_impact_levelHasConcern(partition, roleAssignments, propertyAssignments);
				case 7: return new Enabling_impact_levelHasConcern(partition, roleAssignments, propertyAssignments);
				case 8: return new Immediate_impact_levelHasConcern(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "Company.Assignment_test.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return Assignment_testDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (Assignment_testDomainModel.resourceManager == null)
				{
					Assignment_testDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(Assignment_testDomainModel).Assembly);
				}
				return Assignment_testDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return Assignment_testDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return Assignment_testDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (Assignment_testDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new Assignment_testCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					Assignment_testDomainModel.copyClosure = copyFilter;
				}
				return Assignment_testDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (Assignment_testDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new Assignment_testDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					Assignment_testDomainModel.removeClosure = removeFilter;
				}
				return Assignment_testDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::Company.Assignment_test.FixUpDiagram));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::Company.Assignment_test.FixUpDiagram));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class Assignment_testDeleteClosure : Assignment_testDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public Assignment_testDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class Assignment_testDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public Assignment_testDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::Company.Assignment_test.SoSAHasElements.ElementDomainRoleId, true);
			DomainRoles.Add(global::Company.Assignment_test.Systematic_impact_levelHasEnabling_impact_level.Enabling_impact_levelDomainRoleId, true);
			DomainRoles.Add(global::Company.Assignment_test.Enabling_impact_levelHasImmediate_impact_level.Immediate_impact_levelDomainRoleId, true);
			DomainRoles.Add(global::Company.Assignment_test.Immediate_impact_levelHasSolution_name.Solution_nameDomainRoleId, true);
			DomainRoles.Add(global::Company.Assignment_test.Systematic_impact_levelHasConcern.ConcernDomainRoleId, true);
			DomainRoles.Add(global::Company.Assignment_test.Enabling_impact_levelHasConcern.ConcernDomainRoleId, true);
			DomainRoles.Add(global::Company.Assignment_test.Immediate_impact_levelHasConcern.ConcernDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class Assignment_testCopyClosure : Assignment_testCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public Assignment_testCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class Assignment_testCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public Assignment_testCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}

