//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace Company.Assignment_test
{
	/// <summary>
	/// DomainClass SoSA
	/// The root in which all other elements are embedded. Appears as a diagram.
	/// </summary>
	[DslDesign::DisplayNameResource("Company.Assignment_test.SoSA.DisplayName", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Company.Assignment_test.SoSA.Description", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Company.Assignment_test.Assignment_testDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("d71fa1e2-345f-4feb-96ad-4b831f761d85")]
	public partial class SoSA : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// SoSA domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xd71fa1e2, 0x345f, 0x4feb, 0x96, 0xad, 0x4b, 0x83, 0x1f, 0x76, 0x1d, 0x85);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public SoSA(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public SoSA(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Elements opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Elements.
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Systematic_impact_level> Elements
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Systematic_impact_level>, Systematic_impact_level>(global::Company.Assignment_test.SoSAHasElements.SoSADomainRoleId);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::Company.Assignment_test.Systematic_impact_level.DomainClassId)) 
				{
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::Company.Assignment_test.Systematic_impact_level sourceSystematic_impact_level1 = sourceElement as global::Company.Assignment_test.Systematic_impact_level;
			if (sourceSystematic_impact_level1 != null)
			{
				// Create link for path SoSAHasElements.Elements
				this.Elements.Add(sourceSystematic_impact_level1);

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::Company.Assignment_test.Systematic_impact_level sourceSystematic_impact_level1 = sourceElement as global::Company.Assignment_test.Systematic_impact_level;
			if (sourceSystematic_impact_level1 != null)
			{
				// Delete link for path SoSAHasElements.Elements
				
				foreach (DslModeling::ElementLink link in global::Company.Assignment_test.SoSAHasElements.GetLinks((global::Company.Assignment_test.SoSA)this, sourceSystematic_impact_level1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::Company.Assignment_test.SoSAHasElements.SoSADomainRoleId, global::Company.Assignment_test.SoSAHasElements.ElementDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace Company.Assignment_test
{
	/// <summary>
	/// DomainClass Systematic_impact_level
	/// Elements embedded in the model. Appear as boxes on the diagram.
	/// </summary>
	[DslDesign::DisplayNameResource("Company.Assignment_test.Systematic_impact_level.DisplayName", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Company.Assignment_test.Systematic_impact_level.Description", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Company.Assignment_test.Assignment_testDomainModel))]
	[global::System.CLSCompliant(true)]
	[global::System.Diagnostics.DebuggerDisplay("{GetType().Name,nq} (Name = {namePropertyStorage})")]
	[DslModeling::DomainObjectId("61b26034-8d38-46f3-a11c-f09b4766c397")]
	public partial class Systematic_impact_level : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Systematic_impact_level domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x61b26034, 0x8d38, 0x46f3, 0xa1, 0x1c, 0xf0, 0x9b, 0x47, 0x66, 0xc3, 0x97);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Systematic_impact_level(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Systematic_impact_level(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Name domain property code
		
		/// <summary>
		/// Name domain property Id.
		/// </summary>
		public static readonly global::System.Guid NameDomainPropertyId = new global::System.Guid(0x3ea78053, 0xa5f7, 0x4b54, 0xb4, 0xc6, 0xc6, 0xfd, 0x49, 0xd2, 0x8d, 0x5d);
		
		/// <summary>
		/// Storage for Name
		/// </summary>
		private global::System.String namePropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Name domain property.
		/// Description for Company.Assignment_test.Systematic_impact_level.Name
		/// </summary>
		[DslDesign::DisplayNameResource("Company.Assignment_test.Systematic_impact_level/Name.DisplayName", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("Company.Assignment_test.Systematic_impact_level/Name.Description", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
		[global::System.ComponentModel.DefaultValue("")]
		[DslModeling::ElementName]
		[DslModeling::DomainObjectId("3ea78053-a5f7-4b54-b4c6-c6fd49d28d5d")]
		public global::System.String Name
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return namePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				NamePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Systematic_impact_level.Name domain property.
		/// </summary>
		internal sealed partial class NamePropertyHandler : DslModeling::DomainPropertyValueHandler<Systematic_impact_level, global::System.String>
		{
			private NamePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Systematic_impact_level.Name domain property value handler.
			/// </summary>
			public static readonly NamePropertyHandler Instance = new NamePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Systematic_impact_level.Name domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return NameDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Systematic_impact_level element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.namePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Systematic_impact_level element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.namePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region SoSA opposite domain role accessor
		/// <summary>
		/// Gets or sets SoSA.
		/// </summary>
		public virtual SoSA SoSA
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::Company.Assignment_test.SoSAHasElements.ElementDomainRoleId) as SoSA;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::Company.Assignment_test.SoSAHasElements.ElementDomainRoleId, value);
			}
		}
		#endregion
		#region Targets opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Targets.
		/// Description for Company.Assignment_test.ExampleRelationship.Target
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Systematic_impact_level> Targets
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Systematic_impact_level>, Systematic_impact_level>(global::Company.Assignment_test.Systematic_impact_levelReferencesTargets.SourceDomainRoleId);
			}
		}
		#endregion
		#region Sources opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Sources.
		/// Description for Company.Assignment_test.ExampleRelationship.Source
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Systematic_impact_level> Sources
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Systematic_impact_level>, Systematic_impact_level>(global::Company.Assignment_test.Systematic_impact_levelReferencesTargets.TargetDomainRoleId);
			}
		}
		#endregion
		#region Enabling_impact_level opposite domain role accessor
		/// <summary>
		/// Gets or sets Enabling_impact_level.
		/// Description for
		/// Company.Assignment_test.Systematic_impact_levelHasEnabling_impact_level.Systematic_impact_level
		/// </summary>
		public virtual Enabling_impact_level Enabling_impact_level
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::Company.Assignment_test.Systematic_impact_levelHasEnabling_impact_level.Systematic_impact_levelDomainRoleId) as Enabling_impact_level;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::Company.Assignment_test.Systematic_impact_levelHasEnabling_impact_level.Systematic_impact_levelDomainRoleId, value);
			}
		}
		#endregion
		#region Concern opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Concern.
		/// Description for
		/// Company.Assignment_test.Systematic_impact_levelHasConcern.Systematic_impact_level
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Concern> Concern
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Concern>, Concern>(global::Company.Assignment_test.Systematic_impact_levelHasConcern.Systematic_impact_levelDomainRoleId);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::Company.Assignment_test.Enabling_impact_level.DomainClassId)) 
				{
					// Check that creating a link with this path doesn't cause multiplicity overflow: Systematic_impact_levelHasEnabling_impact_level.Enabling_impact_level
					if (this.Enabling_impact_level != null)
					{
						return false;
					}
					return true;
				}
				
				if (rootElementDomainInfo.IsDerivedFrom(global::Company.Assignment_test.Concern.DomainClassId)) 
				{
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::Company.Assignment_test.Enabling_impact_level sourceEnabling_impact_level1 = sourceElement as global::Company.Assignment_test.Enabling_impact_level;
			if (sourceEnabling_impact_level1 != null)
			{
				// Create link for path Systematic_impact_levelHasEnabling_impact_level.Enabling_impact_level
				this.Enabling_impact_level = sourceEnabling_impact_level1;

				return;
			}
				
			global::Company.Assignment_test.Concern sourceConcern2 = sourceElement as global::Company.Assignment_test.Concern;
			if (sourceConcern2 != null)
			{
				// Create link for path Systematic_impact_levelHasConcern.Concern
				this.Concern.Add(sourceConcern2);

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::Company.Assignment_test.Enabling_impact_level sourceEnabling_impact_level1 = sourceElement as global::Company.Assignment_test.Enabling_impact_level;
			if (sourceEnabling_impact_level1 != null)
			{
				// Delete link for path Systematic_impact_levelHasEnabling_impact_level.Enabling_impact_level
				
				foreach (DslModeling::ElementLink link in global::Company.Assignment_test.Systematic_impact_levelHasEnabling_impact_level.GetLinks((global::Company.Assignment_test.Systematic_impact_level)this, sourceEnabling_impact_level1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::Company.Assignment_test.Systematic_impact_levelHasEnabling_impact_level.Systematic_impact_levelDomainRoleId, global::Company.Assignment_test.Systematic_impact_levelHasEnabling_impact_level.Enabling_impact_levelDomainRoleId);
				}

				return;
			}
				
			global::Company.Assignment_test.Concern sourceConcern2 = sourceElement as global::Company.Assignment_test.Concern;
			if (sourceConcern2 != null)
			{
				// Delete link for path Systematic_impact_levelHasConcern.Concern
				
				foreach (DslModeling::ElementLink link in global::Company.Assignment_test.Systematic_impact_levelHasConcern.GetLinks((global::Company.Assignment_test.Systematic_impact_level)this, sourceConcern2))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::Company.Assignment_test.Systematic_impact_levelHasConcern.Systematic_impact_levelDomainRoleId, global::Company.Assignment_test.Systematic_impact_levelHasConcern.ConcernDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace Company.Assignment_test
{
	/// <summary>
	/// DomainClass Enabling_impact_level
	/// Description for Company.Assignment_test.Enabling_impact_level
	/// </summary>
	[DslDesign::DisplayNameResource("Company.Assignment_test.Enabling_impact_level.DisplayName", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Company.Assignment_test.Enabling_impact_level.Description", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Company.Assignment_test.Assignment_testDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("d8aaa10a-ce4d-48f0-80b1-11445f49fb35")]
	public partial class Enabling_impact_level : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Enabling_impact_level domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xd8aaa10a, 0xce4d, 0x48f0, 0x80, 0xb1, 0x11, 0x44, 0x5f, 0x49, 0xfb, 0x35);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Enabling_impact_level(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Enabling_impact_level(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Systematic_impact_level opposite domain role accessor
		/// <summary>
		/// Gets or sets Systematic_impact_level.
		/// Description for
		/// Company.Assignment_test.Systematic_impact_levelHasEnabling_impact_level.Enabling_impact_level
		/// </summary>
		public virtual Systematic_impact_level Systematic_impact_level
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::Company.Assignment_test.Systematic_impact_levelHasEnabling_impact_level.Enabling_impact_levelDomainRoleId) as Systematic_impact_level;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::Company.Assignment_test.Systematic_impact_levelHasEnabling_impact_level.Enabling_impact_levelDomainRoleId, value);
			}
		}
		#endregion
		#region Immediate_impact_level opposite domain role accessor
		/// <summary>
		/// Gets or sets Immediate_impact_level.
		/// Description for
		/// Company.Assignment_test.Enabling_impact_levelHasImmediate_impact_level.Enabling_impact_level
		/// </summary>
		public virtual Immediate_impact_level Immediate_impact_level
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::Company.Assignment_test.Enabling_impact_levelHasImmediate_impact_level.Enabling_impact_levelDomainRoleId) as Immediate_impact_level;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::Company.Assignment_test.Enabling_impact_levelHasImmediate_impact_level.Enabling_impact_levelDomainRoleId, value);
			}
		}
		#endregion
		#region Concern opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Concern.
		/// Description for
		/// Company.Assignment_test.Enabling_impact_levelHasConcern.Enabling_impact_level
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Concern> Concern
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Concern>, Concern>(global::Company.Assignment_test.Enabling_impact_levelHasConcern.Enabling_impact_levelDomainRoleId);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::Company.Assignment_test.Immediate_impact_level.DomainClassId)) 
				{
					// Check that creating a link with this path doesn't cause multiplicity overflow: Enabling_impact_levelHasImmediate_impact_level.Immediate_impact_level
					if (this.Immediate_impact_level != null)
					{
						return false;
					}
					return true;
				}
				
				if (rootElementDomainInfo.IsDerivedFrom(global::Company.Assignment_test.Concern.DomainClassId)) 
				{
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::Company.Assignment_test.Immediate_impact_level sourceImmediate_impact_level1 = sourceElement as global::Company.Assignment_test.Immediate_impact_level;
			if (sourceImmediate_impact_level1 != null)
			{
				// Create link for path Enabling_impact_levelHasImmediate_impact_level.Immediate_impact_level
				this.Immediate_impact_level = sourceImmediate_impact_level1;

				return;
			}
				
			global::Company.Assignment_test.Concern sourceConcern2 = sourceElement as global::Company.Assignment_test.Concern;
			if (sourceConcern2 != null)
			{
				// Create link for path Enabling_impact_levelHasConcern.Concern
				this.Concern.Add(sourceConcern2);

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::Company.Assignment_test.Immediate_impact_level sourceImmediate_impact_level1 = sourceElement as global::Company.Assignment_test.Immediate_impact_level;
			if (sourceImmediate_impact_level1 != null)
			{
				// Delete link for path Enabling_impact_levelHasImmediate_impact_level.Immediate_impact_level
				
				foreach (DslModeling::ElementLink link in global::Company.Assignment_test.Enabling_impact_levelHasImmediate_impact_level.GetLinks((global::Company.Assignment_test.Enabling_impact_level)this, sourceImmediate_impact_level1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::Company.Assignment_test.Enabling_impact_levelHasImmediate_impact_level.Enabling_impact_levelDomainRoleId, global::Company.Assignment_test.Enabling_impact_levelHasImmediate_impact_level.Immediate_impact_levelDomainRoleId);
				}

				return;
			}
				
			global::Company.Assignment_test.Concern sourceConcern2 = sourceElement as global::Company.Assignment_test.Concern;
			if (sourceConcern2 != null)
			{
				// Delete link for path Enabling_impact_levelHasConcern.Concern
				
				foreach (DslModeling::ElementLink link in global::Company.Assignment_test.Enabling_impact_levelHasConcern.GetLinks((global::Company.Assignment_test.Enabling_impact_level)this, sourceConcern2))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::Company.Assignment_test.Enabling_impact_levelHasConcern.Enabling_impact_levelDomainRoleId, global::Company.Assignment_test.Enabling_impact_levelHasConcern.ConcernDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace Company.Assignment_test
{
	/// <summary>
	/// DomainClass Immediate_impact_level
	/// Description for Company.Assignment_test.Immediate_impact_level
	/// </summary>
	[DslDesign::DisplayNameResource("Company.Assignment_test.Immediate_impact_level.DisplayName", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Company.Assignment_test.Immediate_impact_level.Description", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Company.Assignment_test.Assignment_testDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("a8637332-15ed-43bb-a945-f80578653d16")]
	public partial class Immediate_impact_level : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Immediate_impact_level domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xa8637332, 0x15ed, 0x43bb, 0xa9, 0x45, 0xf8, 0x05, 0x78, 0x65, 0x3d, 0x16);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Immediate_impact_level(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Immediate_impact_level(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Enabling_impact_level opposite domain role accessor
		/// <summary>
		/// Gets or sets Enabling_impact_level.
		/// Description for
		/// Company.Assignment_test.Enabling_impact_levelHasImmediate_impact_level.Immediate_impact_level
		/// </summary>
		public virtual Enabling_impact_level Enabling_impact_level
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::Company.Assignment_test.Enabling_impact_levelHasImmediate_impact_level.Immediate_impact_levelDomainRoleId) as Enabling_impact_level;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::Company.Assignment_test.Enabling_impact_levelHasImmediate_impact_level.Immediate_impact_levelDomainRoleId, value);
			}
		}
		#endregion
		#region Solution_name opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Solution_name.
		/// Description for
		/// Company.Assignment_test.Immediate_impact_levelHasSolution_name.Immediate_impact_level
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Solution_name> Solution_name
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Solution_name>, Solution_name>(global::Company.Assignment_test.Immediate_impact_levelHasSolution_name.Immediate_impact_levelDomainRoleId);
			}
		}
		#endregion
		#region Concern opposite domain role accessor
		
		/// <summary>
		/// Gets a list of Concern.
		/// Description for
		/// Company.Assignment_test.Immediate_impact_levelHasConcern.Immediate_impact_level
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Concern> Concern
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Concern>, Concern>(global::Company.Assignment_test.Immediate_impact_levelHasConcern.Immediate_impact_levelDomainRoleId);
			}
		}
		#endregion
		#region ElementGroupPrototype Merge methods
		/// <summary>
		/// Returns a value indicating whether the source element represented by the
		/// specified root ProtoElement can be added to this element.
		/// </summary>
		/// <param name="rootElement">
		/// The root ProtoElement representing a source element.  This can be null, 
		/// in which case the ElementGroupPrototype does not contain an ProtoElements
		/// and the code should inspect the ElementGroupPrototype context information.
		/// </param>
		/// <param name="elementGroupPrototype">The ElementGroupPrototype that contains the root ProtoElement.</param>
		/// <returns>true if the source element represented by the ProtoElement can be added to this target element.</returns>
		protected override bool CanMerge(DslModeling::ProtoElementBase rootElement, DslModeling::ElementGroupPrototype elementGroupPrototype)
		{
			if ( elementGroupPrototype == null ) throw new global::System.ArgumentNullException("elementGroupPrototype");
			
			if (rootElement != null)
			{
				DslModeling::DomainClassInfo rootElementDomainInfo = this.Partition.DomainDataDirectory.GetDomainClass(rootElement.DomainClassId);
				
				if (rootElementDomainInfo.IsDerivedFrom(global::Company.Assignment_test.Solution_name.DomainClassId)) 
				{
					return true;
				}
				
				if (rootElementDomainInfo.IsDerivedFrom(global::Company.Assignment_test.Concern.DomainClassId)) 
				{
					return true;
				}
			}
			return base.CanMerge(rootElement, elementGroupPrototype);
		}
		
		/// <summary>
		/// Called by the Merge process to create a relationship between 
		/// this target element and the specified source element. 
		/// Typically, a parent-child relationship is established
		/// between the target element (the parent) and the source element 
		/// (the child), but any relationship can be established.
		/// </summary>
		/// <param name="sourceElement">The element that is to be related to this model element.</param>
		/// <param name="elementGroup">The group of source ModelElements that have been rehydrated into the target store.</param>
		/// <remarks>
		/// This method is overriden to create the relationship between the target element and the specified source element.
		/// The base method does nothing.
		/// </remarks>
		protected override void MergeRelate(DslModeling::ModelElement sourceElement, DslModeling::ElementGroup elementGroup)
		{
			// In general, sourceElement is allowed to be null, meaning that the elementGroup must be parsed for special cases.
			// However this is not supported in generated code.  Use double-deriving on this class and then override MergeRelate completely if you 
			// need to support this case.
			if ( sourceElement == null ) throw new global::System.ArgumentNullException("sourceElement");
		
				
			global::Company.Assignment_test.Solution_name sourceSolution_name1 = sourceElement as global::Company.Assignment_test.Solution_name;
			if (sourceSolution_name1 != null)
			{
				// Create link for path Immediate_impact_levelHasSolution_name.Solution_name
				this.Solution_name.Add(sourceSolution_name1);

				return;
			}
				
			global::Company.Assignment_test.Concern sourceConcern2 = sourceElement as global::Company.Assignment_test.Concern;
			if (sourceConcern2 != null)
			{
				// Create link for path Immediate_impact_levelHasConcern.Concern
				this.Concern.Add(sourceConcern2);

				return;
			}
		
			// Sdk workaround to runtime bug #879350 (DSL: can't copy and paste a MEL that has a MEX). Avoid MergeRelate on ModelElementExtension
			// during a "Paste".
			if (sourceElement is DslModeling::ExtensionElement
				&& sourceElement.Store.TransactionManager.CurrentTransaction.TopLevelTransaction.Context.ContextInfo.ContainsKey("{9DAFD42A-DC0E-4d78-8C3F-8266B2CF8B33}"))
			{
				return;
			}
		
			// Fall through to base class if this class hasn't handled the merge.
			base.MergeRelate(sourceElement, elementGroup);
		}
		
		/// <summary>
		/// Performs operation opposite to MergeRelate - i.e. disconnects a given
		/// element from the current one (removes links created by MergeRelate).
		/// </summary>
		/// <param name="sourceElement">Element to be unmerged/disconnected.</param>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		protected override void MergeDisconnect(DslModeling::ModelElement sourceElement)
		{
			if (sourceElement == null) throw new global::System.ArgumentNullException("sourceElement");
				
			global::Company.Assignment_test.Solution_name sourceSolution_name1 = sourceElement as global::Company.Assignment_test.Solution_name;
			if (sourceSolution_name1 != null)
			{
				// Delete link for path Immediate_impact_levelHasSolution_name.Solution_name
				
				foreach (DslModeling::ElementLink link in global::Company.Assignment_test.Immediate_impact_levelHasSolution_name.GetLinks((global::Company.Assignment_test.Immediate_impact_level)this, sourceSolution_name1))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::Company.Assignment_test.Immediate_impact_levelHasSolution_name.Immediate_impact_levelDomainRoleId, global::Company.Assignment_test.Immediate_impact_levelHasSolution_name.Solution_nameDomainRoleId);
				}

				return;
			}
				
			global::Company.Assignment_test.Concern sourceConcern2 = sourceElement as global::Company.Assignment_test.Concern;
			if (sourceConcern2 != null)
			{
				// Delete link for path Immediate_impact_levelHasConcern.Concern
				
				foreach (DslModeling::ElementLink link in global::Company.Assignment_test.Immediate_impact_levelHasConcern.GetLinks((global::Company.Assignment_test.Immediate_impact_level)this, sourceConcern2))
				{
					// Delete the link, but without possible delete propagation to the element since it's moving to a new location.
					link.Delete(global::Company.Assignment_test.Immediate_impact_levelHasConcern.Immediate_impact_levelDomainRoleId, global::Company.Assignment_test.Immediate_impact_levelHasConcern.ConcernDomainRoleId);
				}

				return;
			}
			// Fall through to base class if this class hasn't handled the unmerge.
			base.MergeDisconnect(sourceElement);
		}
		#endregion
	}
}
namespace Company.Assignment_test
{
	/// <summary>
	/// DomainClass Solution_name
	/// Description for Company.Assignment_test.Solution_name
	/// </summary>
	[DslDesign::DisplayNameResource("Company.Assignment_test.Solution_name.DisplayName", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Company.Assignment_test.Solution_name.Description", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Company.Assignment_test.Assignment_testDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("306c5a82-50ac-482a-9694-91d35880fad0")]
	public partial class Solution_name : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Solution_name domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x306c5a82, 0x50ac, 0x482a, 0x96, 0x94, 0x91, 0xd3, 0x58, 0x80, 0xfa, 0xd0);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Solution_name(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Solution_name(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Immediate_impact_level opposite domain role accessor
		/// <summary>
		/// Gets or sets Immediate_impact_level.
		/// Description for
		/// Company.Assignment_test.Immediate_impact_levelHasSolution_name.Solution_name
		/// </summary>
		public virtual Immediate_impact_level Immediate_impact_level
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::Company.Assignment_test.Immediate_impact_levelHasSolution_name.Solution_nameDomainRoleId) as Immediate_impact_level;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::Company.Assignment_test.Immediate_impact_levelHasSolution_name.Solution_nameDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace Company.Assignment_test
{
	/// <summary>
	/// DomainClass Concern
	/// Description for Company.Assignment_test.Concern
	/// </summary>
	[DslDesign::DisplayNameResource("Company.Assignment_test.Concern.DisplayName", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Company.Assignment_test.Concern.Description", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Company.Assignment_test.Assignment_testDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("20578f92-156e-42cc-883a-b2c453e93110")]
	public partial class Concern : DslModeling::ModelElement
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// Concern domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x20578f92, 0x156e, 0x42cc, 0x88, 0x3a, 0xb2, 0xc4, 0x53, 0xe9, 0x31, 0x10);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Concern(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public Concern(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
		#region Name domain property code
		
		/// <summary>
		/// Name domain property Id.
		/// </summary>
		public static readonly global::System.Guid NameDomainPropertyId = new global::System.Guid(0x5080179d, 0x20ac, 0x412b, 0x82, 0x82, 0x7c, 0x5d, 0x68, 0xf7, 0x93, 0x71);
		
		/// <summary>
		/// Storage for Name
		/// </summary>
		private global::System.String namePropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Name domain property.
		/// Description for Company.Assignment_test.Concern.Name
		/// </summary>
		[DslDesign::DisplayNameResource("Company.Assignment_test.Concern/Name.DisplayName", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("Company.Assignment_test.Concern/Name.Description", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("5080179d-20ac-412b-8282-7c5d68f79371")]
		public global::System.String Name
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return namePropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				NamePropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the Concern.Name domain property.
		/// </summary>
		internal sealed partial class NamePropertyHandler : DslModeling::DomainPropertyValueHandler<Concern, global::System.String>
		{
			private NamePropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the Concern.Name domain property value handler.
			/// </summary>
			public static readonly NamePropertyHandler Instance = new NamePropertyHandler();
		
			/// <summary>
			/// Gets the Id of the Concern.Name domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return NameDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(Concern element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.namePropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(Concern element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.namePropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region TargetConcern opposite domain role accessor
		
		/// <summary>
		/// Gets a list of TargetConcern.
		/// Description for
		/// Company.Assignment_test.ConcernReferencesTargetConcern.SourceConcern
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Concern> TargetConcern
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Concern>, Concern>(global::Company.Assignment_test.ConcernReferencesTargetConcern.SourceConcernDomainRoleId);
			}
		}
		#endregion
		#region SourceConcern opposite domain role accessor
		
		/// <summary>
		/// Gets a list of SourceConcern.
		/// Description for
		/// Company.Assignment_test.ConcernReferencesTargetConcern.TargetConcern
		/// </summary>
		public virtual DslModeling::LinkedElementCollection<Concern> SourceConcern
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return GetRoleCollection<DslModeling::LinkedElementCollection<Concern>, Concern>(global::Company.Assignment_test.ConcernReferencesTargetConcern.TargetConcernDomainRoleId);
			}
		}
		#endregion
		#region Systematic_impact_level opposite domain role accessor
		/// <summary>
		/// Gets or sets Systematic_impact_level.
		/// Description for
		/// Company.Assignment_test.Systematic_impact_levelHasConcern.Concern
		/// </summary>
		public virtual Systematic_impact_level Systematic_impact_level
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::Company.Assignment_test.Systematic_impact_levelHasConcern.ConcernDomainRoleId) as Systematic_impact_level;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::Company.Assignment_test.Systematic_impact_levelHasConcern.ConcernDomainRoleId, value);
			}
		}
		#endregion
		#region Enabling_impact_level opposite domain role accessor
		/// <summary>
		/// Gets or sets Enabling_impact_level.
		/// Description for Company.Assignment_test.Enabling_impact_levelHasConcern.Concern
		/// </summary>
		public virtual Enabling_impact_level Enabling_impact_level
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::Company.Assignment_test.Enabling_impact_levelHasConcern.ConcernDomainRoleId) as Enabling_impact_level;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::Company.Assignment_test.Enabling_impact_levelHasConcern.ConcernDomainRoleId, value);
			}
		}
		#endregion
		#region Immediate_impact_level opposite domain role accessor
		/// <summary>
		/// Gets or sets Immediate_impact_level.
		/// Description for Company.Assignment_test.Immediate_impact_levelHasConcern.Concern
		/// </summary>
		public virtual Immediate_impact_level Immediate_impact_level
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DslModeling::DomainRoleInfo.GetLinkedElement(this, global::Company.Assignment_test.Immediate_impact_levelHasConcern.ConcernDomainRoleId) as Immediate_impact_level;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetLinkedElement(this, global::Company.Assignment_test.Immediate_impact_levelHasConcern.ConcernDomainRoleId, value);
			}
		}
		#endregion
	}
}
namespace Company.Assignment_test
{
	/// <summary>
	/// DomainClass SocialConcern
	/// Description for Company.Assignment_test.SocialConcern
	/// </summary>
	[DslDesign::DisplayNameResource("Company.Assignment_test.SocialConcern.DisplayName", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Company.Assignment_test.SocialConcern.Description", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Company.Assignment_test.Assignment_testDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("575942a3-df2d-4e32-b89d-73a9a129d38d")]
	public partial class SocialConcern : Concern
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// SocialConcern domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x575942a3, 0xdf2d, 0x4e32, 0xb8, 0x9d, 0x73, 0xa9, 0xa1, 0x29, 0xd3, 0x8d);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public SocialConcern(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public SocialConcern(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace Company.Assignment_test
{
	/// <summary>
	/// DomainClass TechnicalConcern
	/// Description for Company.Assignment_test.TechnicalConcern
	/// </summary>
	[DslDesign::DisplayNameResource("Company.Assignment_test.TechnicalConcern.DisplayName", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Company.Assignment_test.TechnicalConcern.Description", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Company.Assignment_test.Assignment_testDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("c8d0fae8-05aa-4c2e-a298-051660a3f301")]
	public partial class TechnicalConcern : Concern
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// TechnicalConcern domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xc8d0fae8, 0x05aa, 0x4c2e, 0xa2, 0x98, 0x05, 0x16, 0x60, 0xa3, 0xf3, 0x01);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public TechnicalConcern(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public TechnicalConcern(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace Company.Assignment_test
{
	/// <summary>
	/// DomainClass EnvironmentalConcern
	/// Description for Company.Assignment_test.EnvironmentalConcern
	/// </summary>
	[DslDesign::DisplayNameResource("Company.Assignment_test.EnvironmentalConcern.DisplayName", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Company.Assignment_test.EnvironmentalConcern.Description", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Company.Assignment_test.Assignment_testDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("2dbe8119-aa7d-4548-add3-c6a17b033715")]
	public partial class EnvironmentalConcern : Concern
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// EnvironmentalConcern domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x2dbe8119, 0xaa7d, 0x4548, 0xad, 0xd3, 0xc6, 0xa1, 0x7b, 0x03, 0x37, 0x15);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public EnvironmentalConcern(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public EnvironmentalConcern(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace Company.Assignment_test
{
	/// <summary>
	/// DomainClass EconomicConcern
	/// Description for Company.Assignment_test.EconomicConcern
	/// </summary>
	[DslDesign::DisplayNameResource("Company.Assignment_test.EconomicConcern.DisplayName", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Company.Assignment_test.EconomicConcern.Description", typeof(global::Company.Assignment_test.Assignment_testDomainModel), "Company.Assignment_test.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Company.Assignment_test.Assignment_testDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("e3b32c2d-1f9a-4877-bb4a-9cdd8ed21860")]
	public partial class EconomicConcern : Concern
	{
		#region Constructors, domain class Id
	
		/// <summary>
		/// EconomicConcern domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xe3b32c2d, 0x1f9a, 0x4877, 0xbb, 0x4a, 0x9c, 0xdd, 0x8e, 0xd2, 0x18, 0x60);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public EconomicConcern(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public EconomicConcern(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
