//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslValidation = global::Microsoft.VisualStudio.Modeling.Validation;
namespace Company.Assignment_test
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class Systematic_impact_level
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateSystematic_impact_levelMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Enabling_impact_level == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						Company.Assignment_test.Assignment_testDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"Systematic_impact_level", this.Name, "Enabling_impact_level"),
						"DSL0001", this);
			}
		} // ValidateSystematic_impact_levelMultiplicity
	} // class Systematic_impact_level
} // Company.Assignment_test

namespace Company.Assignment_test
{
	[DslValidation::ValidationState(DslValidation::ValidationState.Enabled)]
	public partial class Enabling_impact_level
	{
		/// <summary>
		/// Checks that the relationships that have a multiplicity of One or OneMany do actually have a link.
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "Generated code.")]
		[DslValidation::ValidationMethod(DslValidation::ValidationCategories.Open | DslValidation::ValidationCategories.Save | DslValidation::ValidationCategories.Menu)]
		private void ValidateEnabling_impact_levelMultiplicity (DslValidation::ValidationContext context)
		{
			if (this.Immediate_impact_level == null)
			{
				context.LogViolation(DslValidation::ViolationType.Error,
					string.Format(global::System.Globalization.CultureInfo.CurrentCulture, 
						Company.Assignment_test.Assignment_testDomainModel.SingletonResourceManager.GetString("MinimumMultiplicityMissingLink"), 
						"Enabling_impact_level", "", "Immediate_impact_level"),
						"DSL0001", this);
			}
		} // ValidateEnabling_impact_levelMultiplicity
	} // class Enabling_impact_level
} // Company.Assignment_test

	
 