//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.Assignment_test
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "Assignmenttest";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Assignment_test";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Company";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID Assignment_testDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(Assignment_testCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID Assignment_testExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(Assignment_testCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewAssignment_testExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(Assignment_testCommandSetId), 0x0001);
	
		// Package identifier
		public const string Assignment_testPackageId = "0b7715c8-385d-4b6f-a8e5-b875c7badca8";
		
		// Editor factory identifier
		public const string Assignment_testEditorFactoryId = "fd60bbe6-9ddf-4e5d-9cd6-5e97a91c800b";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string Assignment_testModelExplorerToolWindowId = "b2545704-da6a-429c-9ac0-7c2fa9cfd2f1";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.Assignment_test
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string Assignment_testCommandSetId = "bd3d1e23-67a8-4337-868c-6b10dc4a024d";
	}
}